# Generated by Django 2.2.7 on 2019-11-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='PAR')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='PAR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(verbose_name='Sort')),
                ('name', models.CharField(max_length=200, verbose_name='PAR')),
                ('problem', models.TextField(blank=True, verbose_name='Problem')),
                ('action', models.TextField(blank=True, verbose_name='Action')),
                ('result', models.TextField(blank=True, verbose_name='Result')),
                ('skills', models.ManyToManyField(to='par.Skill', verbose_name='Skills')),
            ],
            options={
                'verbose_name': 'PAR',
                'verbose_name_plural': 'PARs',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Job')),
                ('core_skills', models.ManyToManyField(to='par.Skill', verbose_name='Core Skills')),
            ],
        ),
    ]
