# Generated by Django 2.2.7 on 2019-11-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('par', '0002_auto_20191108_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='par',
            name='skills',
            field=models.ManyToManyField(blank=True, to='par.Skill', verbose_name='Skills'),
        ),
    ]
