# Generated by Django 2.2.7 on 2019-11-08 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('par', '0003_auto_20191108_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='par',
            options={'ordering': ['sort_order'], 'verbose_name': 'PAR', 'verbose_name_plural': 'PARs'},
        ),
    ]
