# Generated by Django 2.2.7 on 2019-11-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('par', '0004_auto_20191108_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='par',
            name='sort_order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
