# Generated by Django 2.2.7 on 2019-11-08 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('par', '0005_auto_20191108_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='par',
            options={'ordering': ['number'], 'verbose_name': 'PAR', 'verbose_name_plural': 'PARs'},
        ),
        migrations.RenameField(
            model_name='par',
            old_name='sort_order',
            new_name='number',
        ),
    ]
